name: ci
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci

      - name: Prettier
        run: npm run prettier

      - name: Lint
        run: npm run lint

      - name: Test(type)
        run: npm run compile:check

      - name: Test
        run: npm run test
